# fly.toml app configuration file generated for pokedex on 2024-02-03T13:55:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pokedex'
primary_region = 'ams'

[build]

[deploy]
  strategy = "bluegreen"

[processes]
  app = "node app.js" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "5s"
  interval = "20s"
  method = "GET"
  timeout = "5s"
  path = "/healthcheck"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
